[package]
name = "hardy-gui"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
chrono = { workspace = true }
dirs = { workspace = true }
futures = { workspace = true }
hardy-core = { version = "0.1.0", path = "../hardy-core" }
hardy-ml = { version = "0.1.0", path = "../hardy-ml" }
iced = { workspace = true }
image = { workspace = true }
mimalloc = { workspace = true }
muda = { workspace = true }
notify-rust = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-appender = { workspace = true }
tracing-subscriber = { workspace = true }
tray-icon = { workspace = true }

[dev-dependencies]
approx = { workspace = true }

[lints]
workspace = true
